name: "Build IPA"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install dependencies
        run: |
          brew update
          brew install ldid make

      - name: Build app
        run: |
          xcodebuild \
            -project dirtyZero.xcodeproj \
            -scheme dirtyZero \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            BUILD_DIR=build \
            -derivedDataPath build \
            build

      - name: Find .app
        run: |
          find . -name "*.app"

      - name: Create IPA
        run: |
          set -e
          APP_PATH=$(find build -name "*.app" | head -n 1)
          echo "Using app: $APP_PATH"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r app.ipa Payload
          ls -lah

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: app.ipa
